/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Leak3 */

#ifndef _Included_Leak3
#define _Included_Leak3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Leak3
 * Method:    displayHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Leak3_displayHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
